name: Release

on:
  release:
    types:
      - published

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up dotnet core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Run unit tests
      run: dotnet test --no-restore --verbosity normal
    
    - name: Create NuGet Package
      run: dotnet pack -c Release /p:Version=${{ github.event.release.tag_name }} /p:PackageReleaseNotes="See https://github.com/squadradigital/fake-person-data-sdk/releases/tag/${{ github.event.release.tag_name }}"
      working-directory: ./release

    - name: Archive NuGet Package
      uses: actions/upload-artifact@v1
      with:
        name: Squadra.Person.Data.Sdk
        path: ./release/src/Squadra.Person.Data.Sdk/bin/Release/Squadra.Person.Data.Sdk.${{ github.event.release.tag_name }}.nupkg

    - name: Publish Nuget Package
      run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --no-symbols true
